---
author: "Christina McCosker"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Create panel figure for PLS-DA plots

## Libraries
```{r, message=FALSE, warning=FALSE}
library(mixOmics)
library(tidyverse)
library(gridExtra)
library(reshape2)
```

## Data 
```{r, message=FALSE, warning=FALSE}
cyto <- read.csv("Output Files/cleaned_cytokine.csv")
cytoscale <- read.csv("Output Files/cleaned_cytokine_scaled.csv")
meta <- read.csv("Output Files/metadata_cyto.csv")

# Merge cytokine & metadata 
data <- merge(cyto, meta, by="Sample")
datascale <- merge(cytoscale, meta, by="Sample")

# Prepare data
data_molt <-
  data %>%
  filter(!is.na(molt.stage))

datascale_molt <- 
  datascale %>% 
  filter(!is.na(molt.stage))

data_bc <-
  data %>%
  filter(!is.na(bc_bin))

datascale_bc <-
  datascale %>%
  filter(!is.na(bc_bin))


data_iavneg <-
  data %>% 
  filter(iav=="neg")

datascale_iavneg <-
  datascale %>% 
  filter(iav=="neg")
```

## Plot!
### Molt Stage
```{r}
molt_plsda <- mixOmics::plsda(datascale_molt[,2:10],
                              datascale_molt$molt.stage,
                              scale=FALSE,
                              ncomp=9)
molt_plsda_data <- 
  data.frame(x = molt_plsda$variates$X[,1], 
             y = molt_plsda$variates$X[,2],
             molt.stage = molt_plsda$Y)

# Set x and y axis labels based on prop of variation explained
labelx_molt <- paste("LV1 (", 
                round(abs(molt_plsda$prop_expl_var$X[1]*100), digits=0),
                "%)",
                sep="")

labely_molt <- paste("LV2 (", 
                round(abs(molt_plsda$prop_expl_var$X[2]*100), digits=0),
                "%)",
                sep="")


molt_plsda_ggplot <- 
  ggplot(molt_plsda_data, 
         aes(x=x, y=y, col=molt.stage)) +
  geom_point() +
  stat_ellipse() +
  labs(x=labelx_molt,
       y =labely_molt) +
  scale_color_manual("A. Molt Stage", 
                     values=c("#9d9d9d","#008ba2", "black")) +
  theme_bw() +
  theme(panel.grid=element_blank(),
        legend.position=c(0.14, 0.17))
```

### Body Condition
```{r}
bc_plsda <- mixOmics::plsda(datascale_bc[,2:10],
                            datascale_bc$bc_bin,
                            scale=FALSE,
                            ncomp=9)

bc_plsda_data <- 
  data.frame(x = bc_plsda$variates$X[,1], 
             y = bc_plsda$variates$X[,2],
             bc = bc_plsda$Y)

# Set x and y axis labels based on prop of variation explained
labelx_bc <- paste("LV1 (", 
                round(abs(bc_plsda$prop_expl_var$X[1]*100), digits=0),
                "%)",
                sep="")

labely_bc <- paste("LV2 (", 
                round(abs(bc_plsda$prop_expl_var$X[2]*100), digits=0),
                "%)",
                sep="")

bc_plsda_ggplot <- 
  ggplot(bc_plsda_data, 
         aes(x=x, y=y, col=bc)) +
  geom_point() +
  stat_ellipse() +
  labs(x=labelx_bc,
       y = labely_bc) +
  scale_color_manual("B. Body Condition", 
                     values=c("#9d9d9d","#008ba2", "black")) +
  theme_bw() +
  theme(panel.grid=element_blank(),
        legend.position=c(0.83, 0.82))
```

### IAV
```{r}
iav_plsda <- mixOmics::plsda(datascale[,2:10],
                             datascale$iav,
                             scale=FALSE,
                             ncomp=9)

iav_plsda_data <- 
  data.frame(x = iav_plsda$variates$X[,1], 
             y = iav_plsda$variates$X[,2],
             iav = iav_plsda$Y)

# Set x and y axis labels based on prop of variation explained
labelx_iav <- paste("LV1 (", 
                round(abs(iav_plsda$prop_expl_var$X[1]*100), digits=0),
                "%)",
                sep="")

labely_iav <- paste("LV2 (", 
                round(abs(iav_plsda$prop_expl_var$X[2]*100), digits=0),
                "%)",
                sep="")

iav_plsda_ggplot <- 
  ggplot(iav_plsda_data, 
         aes(x=x, y=y, col=iav)) +
  geom_point() +
  stat_ellipse() +
  labs(x=labelx_iav,
       y =labely_iav) +
  scale_color_manual("C. IAV Status", 
                     values=c("#9d9d9d", "black")) +
  theme_bw() +
  theme(panel.grid=element_blank(),
        legend.position=c(0.14, 0.13))
```

### Combine all plots
```{r}
plsda_plots <- grid.arrange(molt_plsda_ggplot, bc_plsda_ggplot, iav_plsda_ggplot,
                            ncol=2, nrow=2, 
                            layout_matrix=(rbind(c(1,1,2,2), c(NA,3,3,NA))))

ggsave("Figures/plsda_manuscript.jpeg", plsda_plots, width=10, height=8, units="in")
```

# IAV Negative Animals
```{r}
iavneg_plsda <- mixOmics::plsda(datascale_iavneg[,2:10],
                                datascale_iavneg$iavser,
                                scale=FALSE,
                                ncomp=9)

iavneg_plsda_data <- 
  data.frame(x = iavneg_plsda$variates$X[,1], 
             y = iavneg_plsda$variates$X[,2],
             iav = iavneg_plsda$Y)

# Set x and y axis labels based on prop of variation explained
labelx_iavneg <- paste("LV1 (", 
                round(abs(iavneg_plsda$prop_expl_var$X[1]*100), digits=0),
                "%)",
                sep="")

labely_iavneg <- paste("LV2 (", 
                round(abs(iavneg_plsda$prop_expl_var$X[2]*100), digits=0),
                "%)",
                sep="")

iavneg_plsda_ggplot <- 
  ggplot(iavneg_plsda_data, 
         aes(x=x, y=y, col=iav)) +
  geom_point() +
  stat_ellipse() +
  labs(x=labelx_iavneg,
       y =labely_iavneg) +
  scale_color_manual("C. IAV Serology Status", 
                     values=c("#9d9d9d", "black")) +
  theme_bw() +
  theme(panel.grid=element_blank(),
        legend.position=c(0.14, 0.13))
iavneg_plsda_ggplot

# Location
loc_plsda <- mixOmics::plsda(datascale[,2:10],
                            datascale$location,
                            scale=FALSE,
                            ncomp=9)
loc_plsda_data <- 
  data.frame(x = loc_plsda$variates$X[,1], 
             y = loc_plsda$variates$X[,2],
             location = loc_plsda$Y)

# Set x and y axis labels based on prop of variation explained
labelx_loc <- paste("LV1 (", 
                round(abs(loc_plsda$prop_expl_var$X[1]*100), digits=0),
                "%)",
                sep="")

labely_loc <- paste("LV2 (", 
                round(abs(loc_plsda$prop_expl_var$X[2]*100), digits=0),
                "%)",
                sep="")

loc_plsda_ggplot <- 
  ggplot(loc_plsda_data, 
         aes(x=x, y=y, col=location)) +
  geom_point() +
  stat_ellipse() +
  labs(x=labelx_loc,
       y =labelx_loc) +
  scale_color_manual("Location", 
                     values=c("#9d9d9d","#008ba2", "black")) +
  theme_bw() +
  theme(panel.grid=element_blank(),
        legend.position=c(0.12, 0.17))
loc_plsda_ggplot
```
