---
title: "Characterization of gray seal pup cytokine response to influenza A virus"
author: "Christina M. McCosker"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
suppresss-bibliography: true
---

# Publication Information
McCosker et al. (2025). Journal of Widllife Diseases

## Authors
Christina McCosker^1^, Milton Levin^2^, Wendy Puryear^3^, Jonathan Runstadler^3^, Kimberly Murray^4^, Kristina M. Cammen^1^  
*^1^School of Marine Sciences, University of Maine, Orono, ME, USA*  
*^2^ Department of Pathobiology and Veterinary Science, University of Connecticut, Storrs, CT, USA*  
*^3^ Cummings School of Veterinary Medicine, Tufts University, North Grafton, MA, USA*  
*^4^ NOAA Northeast Fisheries Science Center, Woods Hole, MA, USA*  

## Abstract
Infectious disease is a naturally occurring phenomenon in healthy ecosystems, but anthropogenic pressures have led to an increase in the spread and intensity of disease outbreaks in recent decades. Ecosystem health and functioning can be monitored through sentinel organisms, such as marine mammals for coastal environments. In the Northwest Atlantic Ocean  , gray (*Halichoerus grypus*) and harbor (Phoca vitulina) seals are exposed to influenza A virus (IAV) but exhibit apparent differences in disease severity, as gray seals largely remain asymptomatic while harbor seals experience IAV-associated morbidity and mortality. This study aimed to investigate gray seal response to IAV through cytokines, which are signaling proteins responsible for initiating and regulating an immune response. Swabs (nasal, conjunctival, and rectal) and blood samples were collected from wild gray seal pups (n=116) and used to detect IAV infection and to measure 13 serum cytokines. There was no significant difference in cytokine profiles across IAV infection status, age (as determined by molt stage), or body condition (a proxy of overall health), but individual cytokines were identified as important in differentiating between seals across these categorical variables  , and a general trend of lower cytokine detection rates was observed among IAV-infected pups. These results suggest that gray seal pups lack a strong cytokine response during IAV infections. Understanding the immune response of pinnipeds, and mammals more broadly, to viral pathogens is important for predicting how the increased emergence and spread of infectious disease will shape the future of global terrestrial and marine mammal populations.
